default['tz'] = 'Europe/Moscow'
default['cdh_kerberos_cookbook']['java']['repo'] = 'ppa:webupd8team/java'
default['cdh_kerberos_cookbook']['java']['installer'] = 'oracle-java8-installer'
default['cdh_kerberos_cookbook']['java']['jce'] = 'oracle-java8-unlimited-jce-policy'
default['cdh_kerberos_cookbook']['kerberos']['realm'] = 'DEVOPS.EXAMPLE.COM'
default['cdh_kerberos_cookbook']['kerberos']['domain'] = 'localhost'
